apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: sklearn-iris-limit-resources
spec:
  annotations:
    seldon.io/executor: "true"
  name: iris
  predictors:
    - componentSpecs:
        - spec:
            containers:
              - name: classifier
                resources:
                  requests:
                    cpu: 1
                    memory: 500Mi
      graph:
        children: []
        implementation: SKLEARN_SERVER
        modelUri: s3://iris
        envSecretRefName: seldon-init-container-secret
        name: classifier
        svcOrchSpec:
          resources:
            requests:
              cpu: 1
              memory: 300Mi
      name: default
      svcOrchSpec:
        resources:
          requests:
            memory: 200Mi
      replicas: 1